name: Documentation
description: Request docs improvements
title: "[docs] "
labels: [documentation]
body:
  - type: textarea
    id: docs
    attributes:
      label: Documentation change
      description: What docs should change?
    validations:
      required: true
