name: Experiment
description: Propose a new experiment
title: "[experiment] "
labels: [experiment]
body:
  - type: textarea
    id: question
    attributes:
      label: Research question
      description: What should this experiment answer?
    validations:
      required: true
